name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Setup npmrc
      run: echo "//registry.npmjs.org/:always-auth=true \n //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
    - name: build packages
      run: pnpm build
    - name: publish
      run: pnpm release:only
      env:
        GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}