name: Publish Package

on:
  push:
    tags:
      - 'v*'
      - 'next'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'

    - name: Install
      run: pnpm install

    - name: Build
      run: pnpm build
      
    - name: Publish
      run: pnpm release:only
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  docs:
    needs: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install
      run: pnpm install
    
    - name: Build
      run: pnpm build:demo
      
    - name: Pull Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: examples/demo/dist
        BASE_BRANCH: main